name: Deploy Backend to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app:
        description: "App to deploy"
        required: true
        type: choice
        options:
          - service/backend_service_1
          - service/backend_service_2
        default: service/backend_service_1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install root dependencies
        run: yarn install

      - name: Deploy to Render via API
        run: |
          curl -X POST https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }} \
            -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
            -H 'Content-Type: application/json'
